name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Use server-side codebase
      run: cd /var/www/testForActions

    - name: Install dependencies
      run: sudo npm install
      working-directory: /var/www/testForActions

    - name: Run PHP Unit Tests
      run: ./vendor/bin/phpunit tests/exampleTest.php
      working-directory: /var/www/testForActions

    - name: Run JavaScript Tests
      run: npx jest tests/script.test.js
      working-directory: /var/www/testForActions

    - name: Run Snyk Security Tests
      run: ./snyk/snykTest.sh
      working-directory: /var/www/testForActions