name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Fix permissions for test directory
      run: |
        sudo chown -R $USER:$USER /var/www/testForActions
        sudo chmod -R 755 /var/www/testForActions
    - name: Install PHP dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install
      working-directory: /var/www/testForActions

    - name: Install nvm and Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm use --lts
      shell: bash

    - name: Install Node.js dependencies
      run: npm install
      working-directory: /var/www/testForActions

    - name: Run PHP Unit Tests and collect logs
      run: |
        ./vendor/bin/phpunit tests/exampleTest.php > php_test_result.log 2>&1 || touch php_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

    - name: Run JavaScript Tests and collect logs
      run: |
        npx jest tests/script.test.js > js_test_result.log 2>&1 || touch js_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

    - name: Run Snyk Security Tests and collect logs
      run: |
        ./snyk/snykTest.sh > snyk_test_result.log 2>&1 || touch snyk_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

    - name: Collect and insert all test results into MySQL
      run: |
        # Collect PHP results
        php_result=$(<php_test_result.log | tr -d "'\n\r")
        php_status="success"
        php_error_count=$(grep -c "FAILURES" php_test_result.log || echo "無")
        php_error_location=$(grep -oP "at .*\.php:\d+" php_test_result.log || echo "無")
        if grep -q "FAILURES" php_test_result.log; then php_status="failure"; fi

        # Collect JS results
        js_result=$(<js_test_result.log | tr -d "'\n\r")
        js_status="success"
        js_error_count=$(grep -c "FAIL" js_test_result.log || echo "無")
        js_error_location=$(grep -oP "at .*\.js:\d+" js_test_result.log || echo "無")
        if grep -q "FAIL" js_test_result.log; then js_status="failure"; fi

        # Collect Snyk results
        snyk_result=$(<snyk_test_result.log | tr -d "'\n\r")
        snyk_status="success"
        snyk_error_count=$(grep -c "ERROR" snyk_test_result.log || echo "無")
        snyk_error_location=$(grep -oP "at .*:\d+" snyk_test_result.log || echo "無")
        if grep -q "ERROR" snyk_test_result.log; then snyk_status="failure"; fi

        # Get GitHub username and set dynamic table name
        GITHUB_USER=${{ github.actor }}
        TABLE_NAME="test_results_${GITHUB_USER}"

        # Drop table if it exists and recreate it with the correct schema
        mysql -u ci_user -pci_password -D ci_test_reports -e "
          DROP TABLE IF EXISTS \`${TABLE_NAME}\`;
          CREATE TABLE \`${TABLE_NAME}\` (
            id INT AUTO_INCREMENT PRIMARY KEY,
            test_name VARCHAR(255),
            file_name VARCHAR(255),
            line INT,
            error_count VARCHAR(50),
            error_location TEXT,
            result TEXT,
            status VARCHAR(50),
            log TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
        "

        # Insert formatted results into the database
        mysql -u ci_user -pci_password -D ci_test_reports -e "
          INSERT INTO \`${TABLE_NAME}\` (test_name, file_name, line, error_count, error_location, result, status, log)
          VALUES 
          ('PHP Unit Tests', 'tests/exampleTest.php', 17, '$php_error_count', '$php_error_location', '$php_result', '$php_status', LOAD_FILE('/var/www/testForActions/php_test_result.log')),
          ('JavaScript Tests', 'tests/script.test.js', 1, '$js_error_count', '$js_error_location', '$js_result', '$js_status', LOAD_FILE('/var/www/testForActions/js_test_result.log')),
          ('Snyk Security Tests', 'snyk/snykTest.sh', 1, '$snyk_error_count', '$snyk_error_location', '$snyk_result', '$snyk_status', LOAD_FILE('/var/www/testForActions/snyk_test_result.log'))
        ;"
      working-directory: /var/www/testForActions
      shell: /usr/bin/bash -e {0}
