name: CI/CD Pipeline

# 定義何時觸發工作流，例如當 push 或 pull request 發生在 master 分支時
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  php-tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install PHP dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install
      working-directory: /var/www/testForActions

    - name: Run PHP Unit Tests and collect logs
      run: |
        ./vendor/bin/phpunit tests/exampleTest.php > php_test_result.log 2>&1 || touch php_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

  js-tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Node.js dependencies
      run: sudo npm install
      working-directory: /var/www/testForActions

    - name: Run JavaScript Tests and collect logs
      run: |
        npx jest tests/script.test.js > js_test_result.log 2>&1 || touch js_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

  snyk-security-tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk Security Tests and collect logs
      run: |
        ./snyk/snykTest.sh > snyk_test_result.log 2>&1 || touch snyk_test_result.log
      working-directory: /var/www/testForActions
      continue-on-error: true

  send-email:
    runs-on: self-hosted
    needs: [php-tests, js-tests, snyk-security-tests]
    if: always()
    steps:
    
    - name: Configure Postfix
      run: |
        echo "postfix postfix/mailname string yourdomain.com" | sudo debconf-set-selections
        echo "postfix postfix/main_mailer_type string 'Internet Site'" | sudo debconf-set-selections

    - name: Install mailutils
      run: sudo apt-get install -y mailutils
      
    - name: Collect all logs
      run: |
        touch all_results.log
        cat php_test_result.log >> all_results.log || true
        cat js_test_result.log >> all_results.log || true
        cat snyk_test_result.log >> all_results.log || true

    - name: Send email with test results
      run: |
        sudo apt-get install -y mailutils
        cat all_results.log | mail -s "CI/CD Pipeline Test Results" vieworld8289@gmail.com 
