name: JavaScript Tests

on:
  workflow_run:
    workflows: ["deployment test server"]
    types: completed

jobs:
  js-tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Fix permissions for test directory
      run: |
        sudo chown -R $USER:$USER /var/www/html/test-website
        sudo chmod -R 755 /var/www/html/test-website

    - name: Install Node.js dependencies
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm use --lts
        npm install
      working-directory: /var/www/html/test-website
      
    - name: Run JavaScript Tests and collect logs
      run: |
        js_start=$(date +%s.%N)
        npx --no-install jest tests/script.test.js > /var/www/testForActions/js_test_result.log 2>&1 || touch /var/www/testForActions/js_test_result.log
        js_end=$(date +%s.%N)
        js_duration=$(echo "$js_end - $js_start" | bc)
        echo "JS Time: ${js_duration}s"
      working-directory: /var/www/html/test-website
      continue-on-error: true

  insert-sql-js:
    uses: Huitney/testForActions/.github/workflows/insertSQL.yml@master
    with:
      name: 'js'
    needs: js-tests
