name: Snyk Security Tests

on:
  workflow_run:
    workflows: ["SonarQube Scan"]
    types: completed

jobs:
  snyk-security-tests:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Fix permissions for test directory
      run: |
        sudo chown -R $USER:$USER /var/www/html/test-website
        sudo chmod -R 755 /var/www/html/test-website

    - name: Run Snyk Security Tests and collect logs
      run: |
        snyk_start=$(date +%s.%N)
        ./snyk/snykTest.sh > /var/www/testForActions/snyk_test_result.log 2>&1 || touch /var/www/testForActions/snyk_test_result.log
        snyk_end=$(date +%s.%N)
        snyk_duration=$(echo "$snyk_end - $snyk_start" | bc)
        echo "Snyk Time: ${snyk_duration}s"
      working-directory: /var/www/html/test-website
      continue-on-error: true

  insert-sql-snyk:
    uses: Huitney/testForActions/.github/workflows/insertSQL.yml@master
    with:
      name: 'snyk'
    needs: snyk-security-tests
