name: SonarQube Scan

on:
  workflow_run:
    workflows: ["deployment test server"]
    types: completed

jobs:
  sonarqube-scan:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Fix permissions for test directory
      run: |
        sudo chown -R $USER:$USER /var/www/html/test-website
        sudo chmod -R 755 /var/www/html/test-website

    - name: Ensure SonarScanner is installed
      run: |
        if ! [ -f /usr/local/bin/sonar-scanner ]; then
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
        fi

    - name: Run SonarQube Scanner and collect logs
      run: |
        sonar_start=$(date +%s.%N)
        /usr/local/bin/sonar-scanner \
          -Dsonar.projectBaseDir=/var/www/html/test-website \
          -Dsonar.projectKey=sonar.cpd.cross_project \
          -Dsonar.sources=. \
          -Dsonar.exclusions=**/node_modules/**,**/vendor/**,**/test-results/** \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          > /var/www/testForActions/sonarqube_test_result.log 2>&1 || touch /var/www/testForActions/sonarqube_test_result.log
        sonar_end=$(date +%s.%N)
        sonar_duration=$(echo "$sonar_end - $sonar_start" | bc)
        echo "SonarQube Time: ${sonar_duration}s" >> /var/www/testForActions/sonarqube_test_result.log
      working-directory: /var/www/html/test-website
      continue-on-error: true

    - name: Append SonarQube summary to log
      run: |
        echo -e "\n=== SonarQube Summary Metrics ===" >> /var/www/testForActions/sonarqube_test_result.log

        curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "http://localhost:9000/api/measures/component?component=test-website&metricKeys=coverage,reliability_rating,security_rating,sqale_rating,duplicated_lines_density" \
          | jq -r '.component.measures[] | "\(.metric): \(.value)"' \
          >> /var/www/testForActions/sonarqube_test_result.log

  insert-sql-sonarqube:
    uses: Huitney/testForActions/.github/workflows/insertSQL.yml@master
    with:
      name: 'sonarqube'
    needs: sonarqube-scan
