name: SonarQube Scan

on:
  workflow_run:
    workflows: ["deployment test server"]
    types: completed
    
jobs:
  sonarqube-scan:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Fix permissions for test directory
      run: |
        sudo chown -R $USER:$USER /var/www/html/test-website
        sudo chmod -R 755 /var/www/html/test-website

    - name: Run SonarQube Scanner and collect logs
      run: |
        sonar_start=$(date +%s.%N)
        /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectBaseDir=/var/www/html/test-website \
          -Dsonar.projectKey=test-website \
          -Dsonar.sources=src \
          -Dsonar.exclusions=**/node_modules/**,**/vendor/**,**/test-results/** \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} > /var/www/testForActions/sonarqube_test_result.log 2>&1 || touch /var/www/testForActions/sonarqube_test_result.log
        sonar_end=$(date +%s.%N)
        sonar_duration=$(echo "$sonar_end - $sonar_start" | bc)
        echo "SonarQube Time: ${sonar_duration}s"
      working-directory: /var/www/html/test-website
      continue-on-error: true

  insert-sql-sonarqube:
    uses: Huitney/testForActions/.github/workflows/insertSQL.yml@master
    with:
      name: 'sonarqube'
    needs: sonarqube-scan
