name: deployment test server
on:
  push:
    branches:
      - master
    
jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Fix Git permissions
      run: sudo chown -R $(whoami) /var/www/testForActions/.git
      working-directory: /var/www/testForActions
      
    - name: pull the code
      run: |
        git stash
        git pull origin master
        
      working-directory: /var/www/testForActions
    
    - name: move the code
      run: |
        rm -r .
        mv /var/www/testForActions/test-website .
        
      working-directory: /var/www/html/test-website