name: deployment test server

on:
  push:
    branches:
      - master
    
jobs:
  deployment:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Fix Git permissions
      run:  |
        sudo chown -R $(whoami) /var/www/testForActions/.git
        sudo chown -R $(whoami) /var/www/testForActions
      working-directory: /var/www/testForActions
      
    - name: pull the code
      run: |
        git stash
        git pull origin master
        
      working-directory: /var/www/testForActions
      
    - name: Fix permissions for /var/www/html
      run: sudo chown -R $(whoami) /var/www/html
    
    - name: move the code
      run: |
        rsync -av /var/www/testForActions/test-website/ ./test-website/
        
      working-directory: /var/www/html