name: insertSQL
on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: completed
    
jobs:
  insert-SQL:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Collect and insert all test results into MySQL
      run: |
        
        LOG_DIR="/var/www/testForActions"
        GITHUB_USER=${{ github.actor }}
        TABLE_NAME="test_results_${GITHUB_USER}"
        
        for file in php_test_result.log js_test_result.log snyk_test_result.log; do
          if [ ! -f "$LOG_DIR/$file" ]; then
            echo "Error: $file is missing."
            exit 1
          fi
        done

        collect_results() {
          local test_name="$1"
          local log_file="$LOG_DIR/$2"

          status="success"
          error_count=$(grep -c "ERROR\|FAIL" "$log_file" || echo "0")
          error_location=$(grep -oP "at .*:\d+" "$log_file" || echo "無")
          line=$(grep -oP "(?<=:)\d+" "$log_file" | tr '\n' ',' | sed 's/,$//' || echo "NULL")
          log_content=$(tr -d "'\n\r" < "$log_file")

          if grep -q "ERROR\|FAIL" "$log_file"; then status="failure"; fi

          echo "('$test_name', '$LOG_DIR', '$line', '$error_count', '$error_location', '$status', '$log_content')"
        }

        php_result=$(collect_results "PHP Unit Tests" "php_test_result.log")
        js_result=$(collect_results "JavaScript Tests" "js_test_result.log")
        snyk_result=$(collect_results "Snyk Security Tests" "snyk_test_result.log")

        # Create table if not exists
        mysql -u ci_user -pci_password -D ci_test_reports -e "
        CREATE TABLE IF NOT EXISTS \`${TABLE_NAME}\` (
          id INT AUTO_INCREMENT PRIMARY KEY,
          test_name VARCHAR(255),
          test_location VARCHAR(255),
          line VARCHAR(255) DEFAULT NULL,
          error_count VARCHAR(50),
          error_location TEXT,
          status VARCHAR(50),
          log TEXT,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );"

        # 批量插入測試結果
        mysql -u ci_user -pci_password -D ci_test_reports -e "
        INSERT INTO \`${TABLE_NAME}\` (test_name, test_location, line, error_count, error_location, status, log)
        VALUES $php_result, $js_result, $snyk_result;"
        
      working-directory: /var/www/testForActions
      shell: /usr/bin/bash -e {0}