name: Manual Triggered Tests

on:
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Build and test
      run: |
        npm install
        npm test

    - name: Analyze with CodeQL
      uses: github/codeql-action/analyze@v1

  snyk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    - name: Run Snyk test
      run: snyk test
